# fly.toml app configuration file generated for persons-app on 2023-08-07T21:27:55+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "persons-app"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
